[package]
name = "file_explorer"
version = "0.1.0"
description = "File Explorer"
authors = ["Conaticus", "ProtogenDelta", ]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
tauri = { version = "2", features = [] }  # Removed "log" feature
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
sysinfo = "0.33.1"
walkdir = "2.3.3"
fuzzy-matcher = "*"
rayon = "1.7.0"
dirs = "5.0.1"
notify = "6.0.1"
tokio = { version = "1.28.2", features = ["full"] }
serde_bencode = "0.2.3"
zstd = "0.12.3"
lazy_static = "1.4.0"
open = "5.3.2"
thiserror = "1.0.40"
tauri-plugin-shell = "2.0.0-rc"
tauri-plugin-dialog = "2.0.0-rc"
log = "0.4"
regex = "1.11.1"

[build-dependencies]
tauri-build = { version = "2", features = [] }  # Removed "log" feature

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
